name: file_system_access
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  js: ^0.6.0
  file_selector: ^0.8.0
  meta: ^1.0.0

dev_dependencies:
  test: ^1.0.0
  lint: ^1.0.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
